[2025-01-12T13:55:33.104+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:55:33.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:55:33.109+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:55:33.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:55:33.146+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:55:33.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:55:33.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:55:33.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.083 seconds
[2025-01-12T13:56:03.216+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:03.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:56:03.219+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:56:03.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:03.230+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:56:03.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:56:03.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:03.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.045 seconds
[2025-01-12T13:56:34.028+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:34.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:56:34.031+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:56:34.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:34.042+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:56:34.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:56:34.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:56:34.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-12T13:57:04.184+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:04.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:57:04.187+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:57:04.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:04.196+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:57:04.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:57:04.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:04.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-12T13:57:34.595+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:34.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:57:34.599+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:57:34.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:34.615+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:57:34.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:57:34.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:57:34.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.050 seconds
[2025-01-12T13:58:05.652+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:05.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:58:05.655+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:58:05.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:05.667+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:58:05.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:58:05.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:05.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-12T13:58:36.602+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:36.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:58:36.606+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:58:36.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:36.620+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:58:36.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:58:36.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:58:36.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-12T13:59:07.410+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:07.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:59:07.413+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:59:07.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:07.440+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:59:07.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:59:07.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:07.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.052 seconds
[2025-01-12T13:59:37.586+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:37.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T13:59:37.589+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:59:37.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:37.602+0000] {logging_mixin.py:190} INFO - [2025-01-12T13:59:37.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T13:59:37.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T13:59:37.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.037 seconds
[2025-01-12T14:00:08.333+0000] {processor.py:186} INFO - Started process (PID=654) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:08.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:00:08.336+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:00:08.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:08.350+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:00:08.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:00:08.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:08.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-12T14:00:39.030+0000] {processor.py:186} INFO - Started process (PID=719) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:39.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:00:39.036+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:00:39.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:39.080+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:00:39.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:00:39.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:00:39.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.087 seconds
[2025-01-12T14:01:09.250+0000] {processor.py:186} INFO - Started process (PID=784) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:09.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:01:09.257+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:01:09.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:09.278+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:01:09.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:01:09.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:09.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-12T14:01:39.744+0000] {processor.py:186} INFO - Started process (PID=848) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:39.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:01:39.748+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:01:39.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:39.764+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:01:39.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:01:39.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:01:39.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-12T14:02:10.009+0000] {processor.py:186} INFO - Started process (PID=913) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:10.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:02:10.014+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:02:10.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:10.028+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:02:10.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:02:10.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:10.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-12T14:02:40.947+0000] {processor.py:186} INFO - Started process (PID=978) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:40.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:02:40.950+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:02:40.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:40.965+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:02:40.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:02:40.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:02:40.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-12T14:03:11.044+0000] {processor.py:186} INFO - Started process (PID=1043) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:11.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:03:11.049+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:03:11.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:11.069+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:03:11.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:03:11.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:11.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.066 seconds
[2025-01-12T14:03:41.573+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:41.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:03:41.576+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:03:41.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:41.590+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:03:41.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:03:41.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:03:41.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.051 seconds
[2025-01-12T14:04:11.986+0000] {processor.py:186} INFO - Started process (PID=1173) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:11.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:04:11.989+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:04:11.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:12.003+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:04:12.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:04:12.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:12.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.053 seconds
[2025-01-12T14:04:42.388+0000] {processor.py:186} INFO - Started process (PID=1238) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:42.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:04:42.393+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:04:42.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:42.416+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:04:42.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:04:42.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:04:42.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.071 seconds
[2025-01-12T14:05:12.880+0000] {processor.py:186} INFO - Started process (PID=1303) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:12.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:05:12.883+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:05:12.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:12.898+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:05:12.894+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:05:12.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:12.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.056 seconds
[2025-01-12T14:05:43.672+0000] {processor.py:186} INFO - Started process (PID=1368) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:43.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:05:43.675+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:05:43.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:43.689+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:05:43.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:05:43.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:05:43.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.051 seconds
[2025-01-12T14:06:13.850+0000] {processor.py:186} INFO - Started process (PID=1433) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:13.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:06:13.854+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:06:13.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:13.866+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:06:13.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:06:13.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:13.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-12T14:06:44.829+0000] {processor.py:186} INFO - Started process (PID=1498) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:44.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:06:44.832+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:06:44.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:44.848+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:06:44.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:06:44.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:06:44.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-12T14:07:15.215+0000] {processor.py:186} INFO - Started process (PID=1563) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:15.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:07:15.218+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:07:15.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:15.232+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:07:15.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:07:15.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:15.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.055 seconds
[2025-01-12T14:07:45.632+0000] {processor.py:186} INFO - Started process (PID=1628) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:45.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:07:45.637+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:07:45.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:45.651+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:07:45.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:07:45.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:07:45.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.054 seconds
[2025-01-12T14:08:16.465+0000] {processor.py:186} INFO - Started process (PID=1693) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:16.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:08:16.469+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:08:16.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:16.485+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:08:16.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:08:16.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:16.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-12T14:08:47.209+0000] {processor.py:186} INFO - Started process (PID=1758) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:47.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:08:47.213+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:08:47.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:47.224+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:08:47.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:08:47.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:08:47.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.037 seconds
[2025-01-12T14:09:17.741+0000] {processor.py:186} INFO - Started process (PID=1823) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:17.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:09:17.745+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:09:17.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:17.756+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:09:17.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:09:17.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:17.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-12T14:09:48.162+0000] {processor.py:186} INFO - Started process (PID=1888) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:48.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:09:48.166+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:09:48.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:48.188+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:09:48.182+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:09:48.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:09:48.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-12T14:13:31.105+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:13:31.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:13:31.117+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:13:31.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:13:31.157+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:13:31.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:13:31.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:13:31.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.111 seconds
[2025-01-12T14:14:02.163+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:02.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:14:02.170+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:14:02.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:02.191+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:14:02.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:14:02.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:02.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.061 seconds
[2025-01-12T14:14:32.495+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:32.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:14:32.499+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:14:32.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:32.515+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:14:32.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:14:32.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:14:32.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.051 seconds
[2025-01-12T14:15:03.062+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:15:03.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-12T14:15:03.066+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:15:03.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:15:03.087+0000] {logging_mixin.py:190} INFO - [2025-01-12T14:15:03.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-12T14:15:03.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-12T14:15:03.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.053 seconds
