[2025-01-16T21:27:35.973+0000] {processor.py:186} INFO - Started process (PID=721) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:27:35.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:27:35.978+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:27:35.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:27:36.000+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:27:35.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:27:36.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:27:36.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.051 seconds
[2025-01-16T21:28:06.095+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:28:06.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:28:06.100+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:28:06.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:28:06.116+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:28:06.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:28:06.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:28:06.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.052 seconds
[2025-01-16T21:30:26.433+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:26.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:30:26.439+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:30:26.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:26.492+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:30:26.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:30:26.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:26.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.104 seconds
[2025-01-16T21:30:57.327+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:57.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:30:57.330+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:30:57.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:57.346+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:30:57.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:30:57.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:30:57.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.043 seconds
[2025-01-16T21:31:27.653+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:27.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:31:27.656+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:31:27.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:27.674+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:31:27.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:31:27.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:27.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.051 seconds
[2025-01-16T21:31:58.359+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:58.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:31:58.365+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:31:58.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:58.386+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:31:58.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:31:58.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:31:58.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.054 seconds
[2025-01-16T21:32:28.813+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:28.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:32:28.817+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:32:28.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:28.844+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:32:28.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:32:28.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:28.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.061 seconds
[2025-01-16T21:32:59.170+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:59.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:32:59.173+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:32:59.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:59.188+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:32:59.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:32:59.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:32:59.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.047 seconds
[2025-01-16T21:33:29.891+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:33:29.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:33:29.895+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:33:29.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:33:29.909+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:33:29.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:33:29.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:33:29.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.040 seconds
[2025-01-16T21:34:00.779+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:00.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:34:00.785+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:34:00.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:00.801+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:34:00.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:34:00.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:00.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.057 seconds
[2025-01-16T21:34:30.930+0000] {processor.py:186} INFO - Started process (PID=601) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:30.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:34:30.934+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:34:30.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:30.957+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:34:30.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:34:30.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:34:30.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.055 seconds
[2025-01-16T21:35:01.527+0000] {processor.py:186} INFO - Started process (PID=666) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:01.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:35:01.530+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:35:01.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:01.544+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:35:01.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:35:01.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:01.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-16T21:35:31.863+0000] {processor.py:186} INFO - Started process (PID=733) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:31.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:35:31.868+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:35:31.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:31.887+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:35:31.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:35:31.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:35:31.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.048 seconds
[2025-01-16T21:36:02.190+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:02.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:36:02.193+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:36:02.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:02.209+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:36:02.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:36:02.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:02.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.042 seconds
[2025-01-16T21:36:32.338+0000] {processor.py:186} INFO - Started process (PID=864) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:32.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:36:32.342+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:36:32.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:32.359+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:36:32.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:36:32.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:36:32.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.057 seconds
[2025-01-16T21:41:57.858+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:41:57.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:41:57.862+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:41:57.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:41:57.887+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:41:57.885+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:41:57.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:41:57.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.076 seconds
[2025-01-16T21:42:28.505+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:28.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:42:28.509+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:42:28.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:28.524+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:42:28.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:42:28.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:28.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.042 seconds
[2025-01-16T21:42:59.415+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:59.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:42:59.418+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:42:59.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:59.435+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:42:59.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:42:59.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:42:59.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.048 seconds
[2025-01-16T21:43:29.814+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:43:29.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:43:29.817+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:43:29.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:43:29.840+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:43:29.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:43:29.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:43:29.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.053 seconds
[2025-01-16T21:44:00.195+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:00.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:44:00.200+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:44:00.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:00.229+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:44:00.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:44:00.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:00.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.062 seconds
[2025-01-16T21:44:30.574+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:30.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:44:30.576+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:44:30.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:30.592+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:44:30.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:44:30.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:44:30.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.039 seconds
[2025-01-16T21:45:01.060+0000] {processor.py:186} INFO - Started process (PID=477) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:01.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:45:01.064+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:45:01.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:01.080+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:45:01.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:45:01.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:01.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.041 seconds
[2025-01-16T21:45:31.519+0000] {processor.py:186} INFO - Started process (PID=544) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:31.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:45:31.524+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:45:31.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:31.546+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:45:31.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:45:31.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:45:31.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.060 seconds
[2025-01-16T21:46:02.324+0000] {processor.py:186} INFO - Started process (PID=611) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:02.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:46:02.328+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:46:02.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:02.349+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:46:02.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:46:02.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:02.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.068 seconds
[2025-01-16T21:46:32.920+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:32.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:46:32.923+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:46:32.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:32.940+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:46:32.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:46:32.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:46:32.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.040 seconds
[2025-01-16T21:47:03.126+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:03.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:47:03.130+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:47:03.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:03.149+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:47:03.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:47:03.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:03.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-16T21:47:33.388+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:33.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:47:33.392+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:47:33.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:33.412+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:47:33.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:47:33.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:47:33.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-16T21:48:03.623+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:03.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:48:03.627+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:48:03.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:03.648+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:48:03.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:48:03.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:03.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.053 seconds
[2025-01-16T21:48:33.900+0000] {processor.py:186} INFO - Started process (PID=947) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:33.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:48:33.908+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:48:33.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:33.931+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:48:33.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:48:33.932+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:48:33.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.064 seconds
[2025-01-16T21:49:04.264+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:04.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:49:04.267+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:49:04.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:04.284+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:49:04.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:49:04.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:04.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.043 seconds
[2025-01-16T21:49:35.145+0000] {processor.py:186} INFO - Started process (PID=1081) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:35.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-16T21:49:35.151+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:49:35.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:35.174+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:49:35.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 29
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:49:35.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-16T21:49:35.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.070 seconds
