[2025-01-16T17:57:22.161+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:22.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:57:22.169+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:57:22.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:22.234+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:57:22.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:57:22.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:22.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.137 seconds
[2025-01-16T17:57:52.474+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:52.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:57:52.477+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:57:52.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:52.501+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:57:52.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:57:52.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:57:52.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.056 seconds
[2025-01-16T17:58:23.124+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:23.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:58:23.127+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:58:23.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:23.146+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:58:23.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:58:23.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:23.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.054 seconds
[2025-01-16T17:58:53.310+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:53.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:58:53.314+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:58:53.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:53.352+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:58:53.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:58:53.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:58:53.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.087 seconds
[2025-01-16T17:59:23.841+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:23.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:59:23.844+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:59:23.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:23.865+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:59:23.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:59:23.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:23.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.060 seconds
[2025-01-16T17:59:54.256+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:54.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T17:59:54.259+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:59:54.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:54.275+0000] {logging_mixin.py:190} INFO - [2025-01-16T17:59:54.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T17:59:54.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T17:59:54.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-16T18:00:24.498+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:24.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:00:24.502+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:00:24.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:24.532+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:00:24.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:00:24.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:24.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.060 seconds
[2025-01-16T18:00:55.487+0000] {processor.py:186} INFO - Started process (PID=526) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:55.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:00:55.490+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:00:55.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:55.510+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:00:55.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:00:55.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:00:55.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.058 seconds
[2025-01-16T18:01:26.092+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:26.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:01:26.095+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:01:26.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:26.117+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:01:26.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:01:26.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:26.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.051 seconds
[2025-01-16T18:01:56.313+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:56.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:01:56.320+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:01:56.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:56.348+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:01:56.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:01:56.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:01:56.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.063 seconds
[2025-01-16T18:02:27.049+0000] {processor.py:186} INFO - Started process (PID=722) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:27.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:02:27.053+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:02:27.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:27.072+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:02:27.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:02:27.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:27.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-16T18:02:57.481+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:57.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:02:57.486+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:02:57.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:57.515+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:02:57.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:02:57.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:02:57.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.071 seconds
[2025-01-16T18:03:27.755+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:27.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:03:27.759+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:03:27.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:27.778+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:03:27.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:03:27.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:27.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.063 seconds
[2025-01-16T18:03:58.117+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:58.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:03:58.129+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:03:58.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:58.160+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:03:58.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:03:58.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:03:58.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.073 seconds
[2025-01-16T18:04:28.671+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:28.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:04:28.674+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:04:28.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:28.691+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:04:28.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:04:28.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:28.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.054 seconds
[2025-01-16T18:04:59.179+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:59.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:04:59.183+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:04:59.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:59.205+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:04:59.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:04:59.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:04:59.224+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-16T18:05:29.852+0000] {processor.py:186} INFO - Started process (PID=1112) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:05:29.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:05:29.856+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:05:29.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:05:29.877+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:05:29.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:05:29.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:05:29.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.050 seconds
[2025-01-16T18:06:00.579+0000] {processor.py:186} INFO - Started process (PID=1177) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:00.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:06:00.582+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:06:00.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:00.605+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:06:00.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:06:00.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:00.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.056 seconds
[2025-01-16T18:06:31.366+0000] {processor.py:186} INFO - Started process (PID=1242) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:31.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-16T18:06:31.370+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:06:31.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:31.397+0000] {logging_mixin.py:190} INFO - [2025-01-16T18:06:31.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-16T18:06:31.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-16T18:06:31.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.063 seconds
