[2025-01-17T14:20:45.108+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:20:45.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:20:45.113+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:20:45.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:20:45.133+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:20:45.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:20:45.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:20:45.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.048 seconds
[2025-01-17T14:21:15.565+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:15.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:21:15.569+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:21:15.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:15.589+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:21:15.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:21:15.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:15.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-17T14:21:46.110+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:46.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:21:46.113+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:21:46.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:46.131+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:21:46.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:21:46.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:21:46.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.055 seconds
[2025-01-17T14:22:15.512+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:15.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:22:15.515+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:22:15.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:15.531+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:22:15.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:22:15.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:15.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.042 seconds
[2025-01-17T14:22:45.980+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:45.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:22:45.986+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:22:45.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:46.005+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:22:46.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:22:46.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:22:46.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.047 seconds
[2025-01-17T14:23:16.477+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:16.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:23:16.482+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:23:16.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:16.508+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:23:16.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:23:16.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:16.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.065 seconds
[2025-01-17T14:23:47.027+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:47.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:23:47.032+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:23:47.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:47.051+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:23:47.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:23:47.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:23:47.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.060 seconds
[2025-01-17T14:26:04.786+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:04.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:26:04.792+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:26:04.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:04.828+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:26:04.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:26:04.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:04.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.113 seconds
[2025-01-17T14:26:35.301+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:35.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:26:35.305+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:26:35.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:35.322+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:26:35.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:26:35.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:26:35.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.050 seconds
[2025-01-17T14:27:05.733+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:05.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:27:05.738+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:27:05.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:05.768+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:27:05.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:27:05.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:05.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.084 seconds
[2025-01-17T14:27:36.187+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:36.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:27:36.191+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:27:36.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:36.213+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:27:36.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:27:36.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:27:36.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.055 seconds
[2025-01-17T14:28:06.614+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:06.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:28:06.620+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:28:06.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:06.637+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:28:06.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:28:06.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:06.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.057 seconds
[2025-01-17T14:28:37.043+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:37.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:28:37.046+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:28:37.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:37.067+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:28:37.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:28:37.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:28:37.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.060 seconds
[2025-01-17T14:29:07.335+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:07.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:29:07.337+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:29:07.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:07.357+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:29:07.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:29:07.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:07.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.045 seconds
[2025-01-17T14:29:37.665+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:37.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:29:37.669+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:29:37.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:37.696+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:29:37.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:29:37.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:29:37.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.059 seconds
[2025-01-17T14:30:07.988+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:07.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:30:07.991+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:30:07.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:08.009+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:30:08.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:30:08.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:08.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-17T14:30:38.410+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:38.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:30:38.412+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:30:38.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:38.431+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:30:38.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:30:38.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:30:38.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.057 seconds
[2025-01-17T14:31:08.816+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:08.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:31:08.819+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:31:08.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:08.839+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:31:08.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:31:08.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:08.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.060 seconds
[2025-01-17T14:31:39.179+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:39.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:31:39.181+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:31:39.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:39.202+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:31:39.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:31:39.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:31:39.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.045 seconds
[2025-01-17T14:38:39.623+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:38:39.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:38:39.633+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:38:39.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:38:39.673+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:38:39.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:38:39.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:38:39.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.119 seconds
[2025-01-17T14:39:10.103+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:10.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:39:10.112+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:39:10.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:10.141+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:39:10.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:39:10.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:10.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.088 seconds
[2025-01-17T14:39:40.536+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:40.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:39:40.541+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:39:40.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:40.582+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:39:40.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:39:40.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:39:40.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.083 seconds
[2025-01-17T14:40:11.027+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:11.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:40:11.030+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:40:11.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:11.051+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:40:11.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:40:11.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:11.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.046 seconds
[2025-01-17T14:40:41.506+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:41.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:40:41.509+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:40:41.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:41.568+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:40:41.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:40:41.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:40:41.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.090 seconds
[2025-01-17T14:41:12.045+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:12.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:41:12.048+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:41:12.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:12.070+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:41:12.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:41:12.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:12.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.048 seconds
[2025-01-17T14:41:42.491+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:42.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:41:42.494+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:41:42.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:42.513+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:41:42.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:41:42.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:41:42.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.061 seconds
[2025-01-17T14:42:12.894+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:12.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:42:12.897+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:42:12.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:12.916+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:42:12.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:42:12.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:12.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.056 seconds
[2025-01-17T14:42:43.357+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:43.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:42:43.365+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:42:43.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:43.389+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:42:43.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:42:43.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:42:43.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.065 seconds
[2025-01-17T14:43:13.794+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:13.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:43:13.797+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:43:13.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:13.814+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:43:13.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:43:13.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:13.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.057 seconds
[2025-01-17T14:43:44.467+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:44.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:43:44.470+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:43:44.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:44.496+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:43:44.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:43:44.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:43:44.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.056 seconds
[2025-01-17T14:44:14.955+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:14.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:44:14.958+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:44:14.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:14.977+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:44:14.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:44:14.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:14.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.045 seconds
[2025-01-17T14:44:45.430+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:45.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:44:45.436+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:44:45.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:45.462+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:44:45.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:44:45.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:44:45.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.061 seconds
[2025-01-17T14:45:15.879+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:15.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:45:15.883+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:45:15.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:15.901+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:45:15.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:45:15.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:15.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.046 seconds
[2025-01-17T14:45:46.289+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:46.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:45:46.293+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:45:46.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:46.312+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:45:46.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:45:46.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:45:46.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.044 seconds
[2025-01-17T14:46:16.713+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:16.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:46:16.717+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:46:16.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:16.736+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:46:16.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:46:16.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:16.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.044 seconds
[2025-01-17T14:46:47.087+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:47.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:46:47.089+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:46:47.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:47.107+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:46:47.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:46:47.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:46:47.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.043 seconds
[2025-01-17T14:47:17.562+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:17.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:47:17.566+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:47:17.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:17.589+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:47:17.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:47:17.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:17.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.058 seconds
[2025-01-17T14:47:47.976+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:47.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:47:47.979+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:47:47.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:47.993+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:47:47.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T14:47:47.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:47:48.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-17T14:48:15.335+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:15.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:48:15.339+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:48:15.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:15.359+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:48:15.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:48:15.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:15.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.047 seconds
[2025-01-17T14:48:45.818+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:45.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:48:45.822+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:48:45.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:45.839+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:48:45.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:48:45.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:48:45.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.042 seconds
[2025-01-17T14:50:07.808+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:07.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:50:07.815+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:50:07.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:07.893+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:50:07.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:50:07.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:07.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.166 seconds
[2025-01-17T14:50:38.395+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:38.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:50:38.398+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:50:38.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:38.418+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:50:38.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:50:38.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:50:38.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.052 seconds
[2025-01-17T14:51:08.910+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:08.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:51:08.915+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:51:08.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:08.944+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:51:08.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:51:08.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:08.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.063 seconds
[2025-01-17T14:51:39.414+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:39.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:51:39.418+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:51:39.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:39.436+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:51:39.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:51:39.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:51:39.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.045 seconds
[2025-01-17T14:52:09.795+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:09.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:52:09.800+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:52:09.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:09.823+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:52:09.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:52:09.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:09.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.069 seconds
[2025-01-17T14:52:40.256+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:40.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:52:40.261+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:52:40.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:40.279+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:52:40.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:52:40.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:52:40.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.056 seconds
[2025-01-17T14:53:10.778+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:10.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:53:10.782+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:53:10.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:10.800+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:53:10.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:53:10.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:10.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.048 seconds
[2025-01-17T14:53:41.234+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:41.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:53:41.239+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:53:41.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:41.263+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:53:41.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:53:41.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:53:41.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.063 seconds
[2025-01-17T14:54:11.692+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:11.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:54:11.696+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:54:11.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:11.714+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:54:11.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:54:11.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:11.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.047 seconds
[2025-01-17T14:54:42.048+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:42.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:54:42.061+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:54:42.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:42.079+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:54:42.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:54:42.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:54:42.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.053 seconds
[2025-01-17T14:55:12.536+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:55:12.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:55:12.539+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:55:12.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:55:12.561+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:55:12.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 133
    ! pip install sqlalchemy
    ^
SyntaxError: invalid syntax
[2025-01-17T14:55:12.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:55:12.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.049 seconds
[2025-01-17T14:57:42.261+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:57:42.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:57:42.266+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:57:42.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:57:42.302+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:57:42.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T14:57:42.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:57:42.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.091 seconds
[2025-01-17T14:58:12.730+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:12.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:58:12.735+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:58:12.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:12.762+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:58:12.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T14:58:12.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:12.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.079 seconds
[2025-01-17T14:58:43.215+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:43.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:58:43.222+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:58:43.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:43.246+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:58:43.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T14:58:43.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:58:43.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.076 seconds
[2025-01-17T14:59:13.694+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:13.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:59:13.697+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:59:13.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:13.717+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:59:13.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T14:59:13.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:13.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.056 seconds
[2025-01-17T14:59:44.079+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:44.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T14:59:44.084+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:59:44.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:44.102+0000] {logging_mixin.py:190} INFO - [2025-01-17T14:59:44.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T14:59:44.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T14:59:44.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.060 seconds
[2025-01-17T15:00:14.562+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:14.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T15:00:14.566+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:00:14.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:14.596+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:00:14.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T15:00:14.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:14.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.067 seconds
[2025-01-17T15:00:45.031+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:45.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T15:00:45.034+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:00:45.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:45.065+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:00:45.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 184
    task_id = 'Extract_data'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T15:00:45.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:00:45.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.076 seconds
[2025-01-17T15:01:14.435+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:01:14.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/Module/CapstoneETL.py for tasks to queue
[2025-01-17T15:01:14.438+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:01:14.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:01:14.459+0000] {logging_mixin.py:190} INFO - [2025-01-17T15:01:14.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/Module/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Module/CapstoneETL.py", line 191
    python_callable=transform_data
                    
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-17T15:01:14.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/Module/CapstoneETL.py
[2025-01-17T15:01:14.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/Module/CapstoneETL.py took 0.051 seconds
