[2025-01-17T10:58:58.699+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:58:58.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T10:58:58.713+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:58.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:58:58.761+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:58.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T10:58:58.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:58:58.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.113 seconds
[2025-01-17T10:59:29.299+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:59:29.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T10:59:29.305+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:29.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:59:29.326+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:29.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T10:59:29.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T10:59:29.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.054 seconds
[2025-01-17T11:00:00.178+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:00.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:00:00.181+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:00.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:00.195+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:00.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:00:00.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:00.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:00:31.120+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:31.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:00:31.128+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:31.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:31.167+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:31.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:00:31.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:00:31.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.091 seconds
[2025-01-17T11:01:01.789+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:01.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:01:01.792+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:01.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:01.807+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:01.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:01:01.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:01.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:01:31.977+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:31.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:01:31.980+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:31.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:31.996+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:31.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:01:31.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:01:32.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.045 seconds
[2025-01-17T11:02:02.091+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:02.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:02:02.096+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:02.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:02.121+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:02.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:02:02.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:02.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.060 seconds
[2025-01-17T11:02:32.668+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:32.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:02:32.671+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:32.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:32.687+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:32.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:02:32.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:02:32.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:03:03.247+0000] {processor.py:186} INFO - Started process (PID=610) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:03.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:03:03.250+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:03.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:03.264+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:03.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:03:03.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:03.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.037 seconds
[2025-01-17T11:03:33.424+0000] {processor.py:186} INFO - Started process (PID=677) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:33.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:03:33.427+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:33.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:33.445+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:33.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:03:33.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:03:33.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:04:03.640+0000] {processor.py:186} INFO - Started process (PID=744) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:03.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:04:03.643+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:03.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:03.658+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:03.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:04:03.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:03.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:04:33.991+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:33.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:04:33.994+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:33.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:34.010+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:34.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:04:34.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:04:34.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:05:04.128+0000] {processor.py:186} INFO - Started process (PID=878) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:04.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:05:04.131+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:04.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:04.147+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:04.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:05:04.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:04.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:05:34.962+0000] {processor.py:186} INFO - Started process (PID=945) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:34.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:05:34.965+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:34.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:34.980+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:34.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:05:34.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:05:34.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:06:05.266+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:05.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:06:05.269+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:05.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:05.284+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:05.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:06:05.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:05.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:06:35.819+0000] {processor.py:186} INFO - Started process (PID=1079) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:35.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:06:35.822+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:35.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:35.836+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:35.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:06:35.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:06:35.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:07:06.018+0000] {processor.py:186} INFO - Started process (PID=1146) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:06.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:07:06.022+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:06.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:06.044+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:06.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:07:06.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:06.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.058 seconds
[2025-01-17T11:07:36.422+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:36.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:07:36.425+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:36.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:36.441+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:36.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:07:36.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:07:36.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.057 seconds
[2025-01-17T11:08:06.664+0000] {processor.py:186} INFO - Started process (PID=1280) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:06.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:08:06.668+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:06.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:06.679+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:06.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:08:06.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:06.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.036 seconds
[2025-01-17T11:08:37.457+0000] {processor.py:186} INFO - Started process (PID=1347) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:37.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:08:37.462+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:37.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:37.481+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:37.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:08:37.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:08:37.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.060 seconds
[2025-01-17T11:09:07.727+0000] {processor.py:186} INFO - Started process (PID=1414) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:07.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:09:07.731+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:07.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:07.745+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:07.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:09:07.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:07.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:09:38.556+0000] {processor.py:186} INFO - Started process (PID=1481) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:38.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:09:38.558+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:38.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:38.574+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:38.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:09:38.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:09:38.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:10:09.214+0000] {processor.py:186} INFO - Started process (PID=1547) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:09.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:10:09.216+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:09.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:09.241+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:09.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:10:09.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:09.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.054 seconds
[2025-01-17T11:10:39.771+0000] {processor.py:186} INFO - Started process (PID=1613) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:39.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:10:39.773+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:39.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:39.790+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:39.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:10:39.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:10:39.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:11:10.481+0000] {processor.py:186} INFO - Started process (PID=1678) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:10.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:11:10.483+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:10.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:10.499+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:10.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:11:10.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:10.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:11:40.969+0000] {processor.py:186} INFO - Started process (PID=1743) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:40.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:11:40.971+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:40.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:40.986+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:40.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:11:40.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:11:41.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:12:11.304+0000] {processor.py:186} INFO - Started process (PID=1808) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:11.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:12:11.306+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:11.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:11.323+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:11.319+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:12:11.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:11.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:12:41.822+0000] {processor.py:186} INFO - Started process (PID=1873) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:41.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:12:41.825+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:41.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:41.845+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:41.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:12:41.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:12:41.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-17T11:13:12.376+0000] {processor.py:186} INFO - Started process (PID=1938) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:12.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:13:12.378+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:12.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:12.396+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:12.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:13:12.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:12.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-17T11:13:42.514+0000] {processor.py:186} INFO - Started process (PID=2003) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:42.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:13:42.516+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:42.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:42.533+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:42.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:13:42.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:13:42.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:14:12.829+0000] {processor.py:186} INFO - Started process (PID=2069) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:12.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:14:12.831+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:12.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:12.846+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:12.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:14:12.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:12.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:14:43.162+0000] {processor.py:186} INFO - Started process (PID=2135) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:43.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:14:43.165+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:43.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:43.182+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:43.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:14:43.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:14:43.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:15:14.320+0000] {processor.py:186} INFO - Started process (PID=2201) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:14.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:15:14.323+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:14.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:14.342+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:14.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:15:14.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:14.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-17T11:15:44.536+0000] {processor.py:186} INFO - Started process (PID=2251) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:44.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:15:44.538+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:44.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:44.554+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:44.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:15:44.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:15:44.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:16:14.835+0000] {processor.py:186} INFO - Started process (PID=2309) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:14.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:16:14.837+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:14.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:14.853+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:14.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:16:14.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:14.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T11:16:45.048+0000] {processor.py:186} INFO - Started process (PID=2372) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:45.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:16:45.050+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:45.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:45.071+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:45.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:16:45.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:16:45.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.047 seconds
[2025-01-17T11:17:15.552+0000] {processor.py:186} INFO - Started process (PID=2438) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:15.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:17:15.554+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:15.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:15.573+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:15.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:17:15.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:15.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:17:46.146+0000] {processor.py:186} INFO - Started process (PID=2504) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:46.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:17:46.149+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:46.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:46.167+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:46.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:17:46.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:17:46.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-17T11:18:16.832+0000] {processor.py:186} INFO - Started process (PID=2570) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:16.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:18:16.834+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:16.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:16.856+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:16.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:18:16.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:16.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.047 seconds
[2025-01-17T11:18:47.312+0000] {processor.py:186} INFO - Started process (PID=2637) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:47.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:18:47.314+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:47.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:47.331+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:47.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:18:47.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:18:47.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:19:18.163+0000] {processor.py:186} INFO - Started process (PID=2703) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:18.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:19:18.165+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:18.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:18.181+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:18.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:19:18.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:18.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:19:48.567+0000] {processor.py:186} INFO - Started process (PID=2769) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:48.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:19:48.569+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:48.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:48.583+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:48.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:19:48.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:19:48.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:20:19.296+0000] {processor.py:186} INFO - Started process (PID=2835) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:19.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:20:19.299+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:19.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:19.315+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:19.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:20:19.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:19.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T11:20:49.443+0000] {processor.py:186} INFO - Started process (PID=2901) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:49.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:20:49.445+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:49.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:49.461+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:49.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:20:49.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:20:49.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:21:20.027+0000] {processor.py:186} INFO - Started process (PID=2967) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:20.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:21:20.030+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:20.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:20.056+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:20.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:21:20.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:20.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.058 seconds
[2025-01-17T11:21:50.370+0000] {processor.py:186} INFO - Started process (PID=3033) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:50.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:21:50.371+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:50.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:50.391+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:50.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:21:50.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:21:50.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:22:20.600+0000] {processor.py:186} INFO - Started process (PID=3100) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:20.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:22:20.602+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:20.602+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:20.632+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:20.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:22:20.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:20.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.052 seconds
[2025-01-17T11:22:51.328+0000] {processor.py:186} INFO - Started process (PID=3166) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:51.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:22:51.331+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:51.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:51.346+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:51.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:22:51.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:22:51.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:23:21.847+0000] {processor.py:186} INFO - Started process (PID=3232) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:21.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:23:21.849+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:21.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:21.867+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:21.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:23:21.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:21.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:23:51.965+0000] {processor.py:186} INFO - Started process (PID=3298) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:51.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:23:51.967+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:51.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:51.983+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:51.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:23:51.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:23:52.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:24:22.630+0000] {processor.py:186} INFO - Started process (PID=3364) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:22.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:24:22.632+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:22.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:22.649+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:22.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:24:22.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:22.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:24:53.549+0000] {processor.py:186} INFO - Started process (PID=3430) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:53.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:24:53.552+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:53.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:53.581+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:53.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:24:53.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:24:53.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.074 seconds
[2025-01-17T11:25:23.991+0000] {processor.py:186} INFO - Started process (PID=3496) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:23.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:25:23.993+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:23.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:24.010+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:24.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:25:24.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:24.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:25:54.355+0000] {processor.py:186} INFO - Started process (PID=3562) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:54.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:25:54.357+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:54.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:54.374+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:54.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:25:54.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:25:54.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:26:24.655+0000] {processor.py:186} INFO - Started process (PID=3628) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:24.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:26:24.657+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:24.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:24.673+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:24.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:26:24.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:24.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:26:54.758+0000] {processor.py:186} INFO - Started process (PID=3693) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:54.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:26:54.760+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:54.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:54.778+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:54.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:26:54.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:26:54.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T11:27:24.992+0000] {processor.py:186} INFO - Started process (PID=3759) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:24.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:27:24.995+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:24.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:25.013+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:25.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:27:25.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:25.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:27:55.547+0000] {processor.py:186} INFO - Started process (PID=3825) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:55.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:27:55.549+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:55.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:55.566+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:55.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:27:55.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:27:55.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:28:26.558+0000] {processor.py:186} INFO - Started process (PID=3891) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:26.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:28:26.559+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:26.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:26.577+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:26.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:28:26.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:26.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:28:56.941+0000] {processor.py:186} INFO - Started process (PID=3957) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:56.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:28:56.945+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:56.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:56.972+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:56.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:28:56.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:28:57.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.073 seconds
[2025-01-17T11:29:27.592+0000] {processor.py:186} INFO - Started process (PID=4024) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:27.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:29:27.594+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:27.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:27.613+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:27.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:29:27.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:27.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:29:58.095+0000] {processor.py:186} INFO - Started process (PID=4090) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:58.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:29:58.097+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:58.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:58.111+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:58.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:29:58.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:29:58.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:40:52.432+0000] {processor.py:186} INFO - Started process (PID=4149) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:40:52.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:40:52.436+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:40:52.460+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:40:52.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:40:52.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.064 seconds
[2025-01-17T11:41:23.120+0000] {processor.py:186} INFO - Started process (PID=4211) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:23.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:41:23.123+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:23.139+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:41:23.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:23.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:41:53.464+0000] {processor.py:186} INFO - Started process (PID=4277) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:53.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:41:53.466+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:53.482+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:41:53.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:41:53.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:42:23.826+0000] {processor.py:186} INFO - Started process (PID=4343) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:23.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:42:23.828+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:23.846+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:42:23.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:23.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T11:42:54.535+0000] {processor.py:186} INFO - Started process (PID=4409) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:54.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:42:54.538+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:54.557+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:42:54.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:42:54.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-17T11:43:24.887+0000] {processor.py:186} INFO - Started process (PID=4475) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:24.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:43:24.890+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:24.910+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:43:24.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:24.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.062 seconds
[2025-01-17T11:43:55.340+0000] {processor.py:186} INFO - Started process (PID=4541) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:55.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:43:55.341+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:55.356+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:43:55.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:43:55.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:44:25.835+0000] {processor.py:186} INFO - Started process (PID=4607) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:25.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:44:25.837+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:25.855+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:44:25.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:25.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:44:56.051+0000] {processor.py:186} INFO - Started process (PID=4673) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:56.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:44:56.053+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:56.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:56.072+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:56.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:44:56.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:44:56.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T11:45:26.739+0000] {processor.py:186} INFO - Started process (PID=4739) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:26.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:45:26.742+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:26.762+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:45:26.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:26.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
[2025-01-17T11:45:57.301+0000] {processor.py:186} INFO - Started process (PID=4805) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:57.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:45:57.303+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:57.320+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:45:57.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:45:57.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:46:27.475+0000] {processor.py:186} INFO - Started process (PID=4871) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:27.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:46:27.477+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:27.491+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:46:27.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:27.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.037 seconds
[2025-01-17T11:46:57.829+0000] {processor.py:186} INFO - Started process (PID=4937) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:57.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:46:57.832+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:57.847+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:46:57.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:46:57.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T11:47:28.228+0000] {processor.py:186} INFO - Started process (PID=5003) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:28.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:47:28.231+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:28.247+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:47:28.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:28.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T11:47:58.388+0000] {processor.py:186} INFO - Started process (PID=5069) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:58.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:47:58.390+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:58.406+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:47:58.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:47:58.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T11:48:28.753+0000] {processor.py:186} INFO - Started process (PID=5135) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:28.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:48:28.755+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:28.773+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:48:28.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:28.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T11:48:59.083+0000] {processor.py:186} INFO - Started process (PID=5201) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:59.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:48:59.085+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:59.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:59.108+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:59.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:48:59.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:48:59.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.052 seconds
[2025-01-17T11:49:29.657+0000] {processor.py:186} INFO - Started process (PID=5267) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:49:29.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T11:49:29.670+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:49:29.740+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T11:49:29.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T11:49:29.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.146 seconds
[2025-01-17T12:03:43.016+0000] {processor.py:186} INFO - Started process (PID=5281) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:03:43.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:03:43.018+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:43.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:03:43.037+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:43.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:03:43.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:03:43.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.053 seconds
[2025-01-17T12:04:13.283+0000] {processor.py:186} INFO - Started process (PID=5347) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:13.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:04:13.285+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:13.299+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:04:13.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:13.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.037 seconds
[2025-01-17T12:04:44.054+0000] {processor.py:186} INFO - Started process (PID=5411) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:44.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:04:44.056+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:44.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:44.074+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:44.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:04:44.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:04:44.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T12:05:14.206+0000] {processor.py:186} INFO - Started process (PID=5477) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:14.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:05:14.208+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:14.228+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:05:14.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:14.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.044 seconds
[2025-01-17T12:05:44.542+0000] {processor.py:186} INFO - Started process (PID=5543) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:44.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:05:44.544+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:44.559+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:05:44.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:05:44.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.038 seconds
[2025-01-17T12:06:14.831+0000] {processor.py:186} INFO - Started process (PID=5609) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:14.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:06:14.833+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:14.849+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:06:14.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:14.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:06:44.933+0000] {processor.py:186} INFO - Started process (PID=5675) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:44.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:06:44.936+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:44.951+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:06:44.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:06:44.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:07:15.390+0000] {processor.py:186} INFO - Started process (PID=5741) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:15.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:07:15.393+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:15.410+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:07:15.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:15.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T12:07:46.168+0000] {processor.py:186} INFO - Started process (PID=5807) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:46.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:07:46.170+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:46.186+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:07:46.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:07:46.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:08:17.048+0000] {processor.py:186} INFO - Started process (PID=5873) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:17.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:08:17.051+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:17.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:17.066+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:17.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:08:17.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:17.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:08:48.057+0000] {processor.py:186} INFO - Started process (PID=5939) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:48.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:08:48.059+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:48.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:48.076+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:48.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:08:48.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:08:48.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.041 seconds
[2025-01-17T12:09:19.086+0000] {processor.py:186} INFO - Started process (PID=6011) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:19.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:09:19.088+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:19.104+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:09:19.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:19.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:09:49.999+0000] {processor.py:186} INFO - Started process (PID=6077) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:50.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:09:50.002+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:50.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:50.018+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:50.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:09:50.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:09:50.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T12:10:20.477+0000] {processor.py:186} INFO - Started process (PID=6143) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:20.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:10:20.480+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:20.496+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:10:20.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:20.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:10:50.911+0000] {processor.py:186} INFO - Started process (PID=6209) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:50.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:10:50.913+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:50.929+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:10:50.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:10:50.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:11:21.370+0000] {processor.py:186} INFO - Started process (PID=6275) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:21.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:11:21.372+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:21.388+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:11:21.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:21.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:11:51.703+0000] {processor.py:186} INFO - Started process (PID=6341) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:51.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:11:51.705+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:51.719+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:11:51.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:11:51.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.038 seconds
[2025-01-17T12:12:22.438+0000] {processor.py:186} INFO - Started process (PID=6407) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:22.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:12:22.440+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:22.456+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:12:22.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:22.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:12:53.507+0000] {processor.py:186} INFO - Started process (PID=6473) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:53.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:12:53.509+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:53.526+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:12:53.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:12:53.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:13:24.273+0000] {processor.py:186} INFO - Started process (PID=6539) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:24.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:13:24.276+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:24.307+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:13:24.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:24.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.087 seconds
[2025-01-17T12:13:55.246+0000] {processor.py:186} INFO - Started process (PID=6605) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:55.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:13:55.249+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:55.264+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:13:55.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:13:55.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:14:25.363+0000] {processor.py:186} INFO - Started process (PID=6671) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:25.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:14:25.365+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:25.381+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:14:25.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:25.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:14:55.653+0000] {processor.py:186} INFO - Started process (PID=6737) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:55.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:14:55.655+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:55.672+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:14:55.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:14:55.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T12:15:26.729+0000] {processor.py:186} INFO - Started process (PID=6803) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:26.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:15:26.731+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:26.747+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:15:26.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:26.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:15:57.036+0000] {processor.py:186} INFO - Started process (PID=6869) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:57.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:15:57.039+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:57.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:57.057+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:57.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:15:57.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:15:57.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.043 seconds
[2025-01-17T12:16:27.894+0000] {processor.py:186} INFO - Started process (PID=6935) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:27.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:16:27.897+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:27.913+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:16:27.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:27.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.040 seconds
[2025-01-17T12:16:58.572+0000] {processor.py:186} INFO - Started process (PID=7001) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:58.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:16:58.574+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:58.590+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:16:58.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:16:58.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.042 seconds
[2025-01-17T12:17:29.345+0000] {processor.py:186} INFO - Started process (PID=7067) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:17:29.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:17:29.347+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:17:29.363+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:17:29.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:17:29.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.039 seconds
[2025-01-17T12:18:00.253+0000] {processor.py:186} INFO - Started process (PID=7133) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:00.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:18:00.255+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:00.274+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:18:00.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:00.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.046 seconds
[2025-01-17T12:18:30.726+0000] {processor.py:186} INFO - Started process (PID=7199) to work on /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:30.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/Capstone_etl_dag.py for tasks to queue
[2025-01-17T12:18:30.729+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:30.750+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/Capstone_etl_dag.py", line 4, in <module>
    from Capstone_project import extract, transform, load  # Import your ETL functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Capstone_project'
[2025-01-17T12:18:30.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/Capstone_etl_dag.py
[2025-01-17T12:18:30.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/Capstone_etl_dag.py took 0.049 seconds
